language: python

python:
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        # We run the tests in 'boxed' mode, i.e. one subprocess per test,
        # because there are memory leaks in Astropy that currently cause the
        # memory to go up to levels that cause the tests to be slow.
        - SETUP_CMD='test -a "--boxed"'
        - NUMPY_VERSION=1.13
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='sip<4.19 aplpy pytest=3.9.3 pytest-xdist astropy-helpers joblib glue-core scipy'
        - CONDA_CHANNELS='astropy-ci-extras astropy glueviz'
        - PIP_DEPENDENCIES='matplotlib<2 Cython https://github.com/radio-astro-tools/pvextractor/archive/master.zip radio_beam https://github.com/astropy/regions/archive/master.zip https://github.com/astropy/reproject/archive/master.zip'
        - SETUP_XVFB=True

    matrix:
        - SETUP_CMD='egg_info'
        - # run with default settings
        - ASTROPY_VERSION='development'
        - CONDA_DEPENDENCIES='pytest=3.9.3 pytest-xdist' PIP_DEPENDENCIES='radio_beam'

matrix:
    include:

        # Do a coverage test in Python 3.
        # make sure *everything* is run for coverage tests
        ## COVERAGE TESTS DISABLED: they don't work any more.  I have found no combination of anything that fixes this.
        - python: 3.6
          env: SETUP_CMD='test --coverage'
               PYTEST_VERSION="<3.10"
               CONDA_DEPENDENCIES='matplotlib aplpy yt bottleneck sip<4.19 aplpy pytest=3.9.3 pytest-xdist astropy-helpers joblib glue-core scipy'
               # pytest 3.9.3 suggested by @e-koch, @astrofrog.  3.10.1 doesn't work, 4.x doesn't work
               # overrode python version too, per bsipocz

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 3.6
          env: SETUP_CMD='build_sphinx -w'

        # test python2.7 with recent numpy version
        - python: 2.7
          env: PIP_DEPENDENCIES='https://github.com/radio-astro-tools/pvextractor/archive/master.zip radio_beam'

        - python: 3.6
          env: NUMPY_VERSION=1.11 ASTROPY_VERSION=LTS CONDA_DEPENDENCIES='matplotlib aplpy bottleneck pytest pytest-xdist astropy-helpers'

        # Test with development versions
        - python: 3.5
          env:
              PIP_DEPENDENCIES='https://github.com/radio-astro-tools/radio_beam/archive/master.zip https://github.com/radio-astro-tools/pvextractor/archive/master.zip'
              ASTROPY_VERSION='development'

        - python: 3.6
          env:
              PIP_DEPENDENCIES='https://github.com/radio-astro-tools/radio_beam/archive/master.zip https://github.com/radio-astro-tools/pvextractor/archive/master.zip'
              ASTROPY_VERSION='development'

        - python: 3.6
          env:
              CONDA_DEPENDENCIES='matplotlib=3 aplpy yt bottleneck pytest pytest-xdist astropy-helpers joblib'
              # installing aplpy via conda will install reproject, so we need to get an appropriate reproject version
              PIP_DEPENDENCIES='https://github.com/radio-astro-tools/radio_beam/archive/master.zip https://github.com/radio-astro-tools/pvextractor/archive/master.zip https://github.com/astropy/reproject/archive/master.zip'
              ASTROPY_VERSION='development'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='spectral_cube/tests/coveragerc'; fi
